### ISSUE TITLE
Build issues in Debian 9.11.0

### ISSUE THREAD

**Issue by ram-sellamuthu** [cbsghost/oce-jt#1]
Hi,

I tried to build your project in DEBIAN v9.11.0 following the steps described in README. But I have not been successful.

Kindly request you to help me with troubleshooting. I am new to DEBIAN and using ninja. where could I find the build log file?
console output is pasted below.
![image](https://user-images.githubusercontent.com/42992796/69914818-8fd0b800-146e-11ea-82f7-dab309ca6e16.png)

Thanks & Regards,
Rajaram

**Comment by cbsghost** [comment]
Umm.... I guess your are using a virtual machine. The console output says it is an internal compiler error. Try increasing the RAM or add larger swap partition to the VM guest.

**Comment by ram-sellamuthu** [comment]
Hi Andy, Thanks for your response and suggestion. Increase in RAM worked like a charm. 

Thanks a ton!
